### PR TITLE
workaround failed to load when upload is not triggered directly by user interaction

### PR DESCRIPTION
**Pull request by normanzb**
the fix is pulled from here:
https://code.google.com/p/in-spirit/source/detail?r=118&path=/trunk/projects/MultipartURLLoader/ru/inspirit/net/MultipartURLLoader.as

### CODE REVIEW

**Comment by Nek-** [comment]
@jonasmonnier notice that you should also merge this.

**Comment by jonasmonnier** [comment]
I see that. Thx.

**Comment by jonasmonnier** [comment]
That's merged. What do you think about Adobe documentation ? It says that the action should only work on user action. Or I miss something?
I added a note in the readme.

**Comment by Nek-** [comment]
Actually, with this patch it does not anymore. That's why it's cool.

**Pull request merged**
